/**
 * Minifies `internal/staticNavigation/runtime.js` into
 * `internal/staticNavigationRuntime.ts`, the constant a static view with
 * `.static({ navigation })` inlines (#865).
 *
 *   bun scripts/build-static-navigation.ts
 *
 * The output is committed, not built at publish time: the string is hashed for
 * Content Security Policies (`STATIC_NAVIGATION_CSP_HASH`), so it must not
 * change with the minifier's version. `staticNavigation.test.ts` checks that it
 * was regenerated after the source changed (by the source's hash) and that it
 * stays in the size budget.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const sourcePath = join(root, "internal/staticNavigation/runtime.js");
const outPath = join(root, "internal/staticNavigationRuntime.ts");

const result = await Bun.build({
  entrypoints: [sourcePath],
  format: "esm",
  target: "browser",
  minify: true,
});
if (!result.success) {
  console.error(result.logs);
  process.exit(1);
}
const code = (await result.outputs[0]!.text()).trim();
const sourceHash = createHash("sha256").update(readFileSync(sourcePath)).digest("hex");

writeFileSync(
  outPath,
  `// Generated by \`bun scripts/build-static-navigation.ts\` from
// \`internal/staticNavigation/runtime.js\`. Do not edit; edit the source and regenerate.
// No imports: \`gemi/testing\` (a browser bundle) and \`gemi stats\` read it too.

/** The sha-256 of the source this was built from, so a test can tell it is stale. */
export const STATIC_NAVIGATION_SOURCE_HASH = ${JSON.stringify(sourceHash)};

/**
 * The navigation runtime (with the island loader) a static view with
 * \`.static({ navigation })\` inlines. Byte-for-byte constant.
 */
export const STATIC_NAVIGATION_SOURCE =
  ${JSON.stringify(code)};
`,
);
console.log(`${outPath}: ${code.length} bytes`);
