services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
      - NODE_ENV=production
      - PORT=3000
    command: >
      sh -c "
        bun run start
      "
