import { describe, expect, test } from "vitest";
import { bucketKey, bucketOf, inRollout, pickVariant, RESOLUTION } from "./bucket";

const subjects = Array.from({ length: 10_000 }, (_, i) => `user-${i}`);

function rolloutShare(percent: number, flagKey = "flag", seed = "seed-a"): number {
  const hits = subjects.filter((subject) =>
    inRollout(bucketOf(bucketKey("rollout", flagKey, seed, "rule-1", subject)), percent),
  );
  return (hits.length / subjects.length) * 100;
}

describe("bucketOf", () => {
  test("is deterministic", () => {
    const key = bucketKey("rollout", "flag", "seed", "rule", "user-1");
    const first = bucketOf(key);

    for (let i = 0; i < 100; i++) {
      expect(bucketOf(key)).toBe(first);
    }
  });

  test("stays within range", () => {
    for (const subject of subjects.slice(0, 500)) {
      const value = bucketOf(bucketKey("rollout", "f", "s", "r", subject));
      expect(value).toBeGreaterThanOrEqual(0);
      expect(value).toBeLessThan(RESOLUTION);
    }
  });

  /**
   * The regression this exists for is invisible at runtime and catastrophic in
   * production: swap the hash, or reorder the key components, and every user is
   * silently re-bucketed mid-rollout. Nothing throws, no test about
   * *distribution* fails, and the only symptom is that the cohort you were
   * measuring quietly became a different cohort.
   *
   * These values were generated by this implementation. If a change makes them
   * fail, that change re-buckets every user of every deployed application — so
   * updating the table is only correct alongside a deliberate migration.
   */
  test("pinned digests — changing these re-buckets every user in production", () => {
    expect(bucketOf(bucketKey("rollout", "flag-a", "seed-a", "rule-1", "user-1"))).toBe(
      bucketOf("rollout:flag-a:seed-a:rule-1:user-1"),
    );

    const pinned: Record<string, number> = {
      "rollout:flag-a:seed-a:rule-1:user-1": 9647,
      "rollout:flag-a:seed-a:rule-1:user-2": 1881,
      "rollout:flag-b:seed-b:rule-1:user-1": 3951,
      "variant:flag-a:seed-a:rule-1:user-1": 7656,
      "rollout:flag-a:seed-a:rule-1:": 7503,
    };

    for (const [key, expected] of Object.entries(pinned)) {
      expect(bucketOf(key), `bucket for "${key}"`).toBe(expected);
    }
  });
});

describe("distribution", () => {
  test("50% lands within two points of half", () => {
    expect(rolloutShare(50)).toBeGreaterThan(48);
    expect(rolloutShare(50)).toBeLessThan(52);
  });

  test("10% lands within one point of a tenth", () => {
    expect(rolloutShare(10)).toBeGreaterThan(9);
    expect(rolloutShare(10)).toBeLessThan(11);
  });

  test("0 and 100 are absolute", () => {
    expect(rolloutShare(0)).toBe(0);
    expect(rolloutShare(100)).toBe(100);
  });

  test("two flags at 50% overlap about a quarter, not a half", () => {
    // Fails immediately if `flagKey` or `seed` stops contributing to the key —
    // which is the bug that makes every 50% rollout hit the same users.
    const inA = new Set(
      subjects.filter((s) =>
        inRollout(bucketOf(bucketKey("rollout", "flag-a", "seed-a", "r", s)), 50),
      ),
    );
    const inBoth = subjects.filter(
      (s) =>
        inA.has(s) && inRollout(bucketOf(bucketKey("rollout", "flag-b", "seed-b", "r", s)), 50),
    );

    const overlap = (inBoth.length / subjects.length) * 100;
    expect(overlap).toBeGreaterThan(23);
    expect(overlap).toBeLessThan(27);
  });

  test("the variant namespace is independent of the rollout gate", () => {
    // Among subjects that passed a 50% rollout, the variant split must still be
    // even. Without the namespace these correlate and the split skews.
    const passed = subjects.filter((s) =>
      inRollout(bucketOf(bucketKey("rollout", "flag", "seed", "r", s)), 50),
    );
    const first = passed.filter(
      (s) =>
        pickVariant(
          [
            { value: "a", weight: 50 },
            { value: "b", weight: 50 },
          ],
          bucketOf(bucketKey("variant", "flag", "seed", "r", s)),
        ) === "a",
    );

    const share = (first.length / passed.length) * 100;
    expect(share).toBeGreaterThan(47);
    expect(share).toBeLessThan(53);
  });

  test("two rules in one flag do not correlate", () => {
    const inFirst = new Set(
      subjects.filter((s) =>
        inRollout(bucketOf(bucketKey("rollout", "flag", "seed", "rule-1", s)), 50),
      ),
    );
    const inBoth = subjects.filter(
      (s) =>
        inFirst.has(s) &&
        inRollout(bucketOf(bucketKey("rollout", "flag", "seed", "rule-2", s)), 50),
    );

    const overlap = (inBoth.length / subjects.length) * 100;
    expect(overlap).toBeGreaterThan(23);
    expect(overlap).toBeLessThan(27);
  });
});

describe("monotonicity", () => {
  test("raising a rollout never removes anyone", () => {
    // What makes a gradual ramp safe: a user who saw the feature at 10% must
    // still see it at 20%. Any scheme that reshuffles fails here.
    for (let percent = 0; percent < 100; percent += 5) {
      const lower = subjects.filter((s) =>
        inRollout(bucketOf(bucketKey("rollout", "f", "s", "r", s)), percent),
      );
      const higher = new Set(
        subjects.filter((s) =>
          inRollout(bucketOf(bucketKey("rollout", "f", "s", "r", s)), percent + 5),
        ),
      );

      for (const subject of lower) {
        expect(higher.has(subject), `${subject} dropped out between ${percent}% and ${percent + 5}%`).toBe(true);
      }
    }
  });
});

describe("pickVariant", () => {
  const even = [
    { value: "a", weight: 50 },
    { value: "b", weight: 50 },
  ];

  test("splits on the boundary", () => {
    expect(pickVariant(even, 0)).toBe("a");
    expect(pickVariant(even, 4999)).toBe("a");
    expect(pickVariant(even, 5000)).toBe("b");
    expect(pickVariant(even, RESOLUTION - 1)).toBe("b");
  });

  test("relative weights are normalised", () => {
    const ones = [
      { value: "a", weight: 1 },
      { value: "b", weight: 1 },
    ];

    for (const bucket of [0, 1234, 4999, 5000, 9999]) {
      expect(pickVariant(ones, bucket)).toBe(pickVariant(even, bucket));
    }
  });

  test("weights need not sum to 100", () => {
    const skewed = [
      { value: "a", weight: 3 },
      { value: "b", weight: 1 },
    ];

    expect(pickVariant(skewed, 7000)).toBe("a");
    expect(pickVariant(skewed, 7600)).toBe("b");
  });

  test("a zero-weight variant is never selected", () => {
    const withZero = [
      { value: "never", weight: 0 },
      { value: "always", weight: 100 },
    ];

    for (let bucket = 0; bucket < RESOLUTION; bucket += 97) {
      expect(pickVariant(withZero, bucket)).toBe("always");
    }
  });

  test("the last variant absorbs rounding drift", () => {
    // Three-way split: each boundary floors, so the top few buckets would be
    // unassigned without the trailing return.
    const thirds = [
      { value: "a", weight: 1 },
      { value: "b", weight: 1 },
      { value: "c", weight: 1 },
    ];

    expect(pickVariant(thirds, RESOLUTION - 1)).toBe("c");
  });

  test("every bucket maps to some variant", () => {
    const thirds = [
      { value: "a", weight: 1 },
      { value: "b", weight: 1 },
      { value: "c", weight: 1 },
    ];

    for (let bucket = 0; bucket < RESOLUTION; bucket++) {
      expect(pickVariant(thirds, bucket)).not.toBe(null);
    }
  });

  test("refuses distributions it cannot express", () => {
    expect(pickVariant([], 0)).toBe(null);
    expect(pickVariant([{ value: "a", weight: 0 }], 0)).toBe(null);
    expect(pickVariant([{ value: "a", weight: -1 }], 0)).toBe(null);
    expect(pickVariant([{ value: "a", weight: Number.NaN }], 0)).toBe(null);
  });
});
