import { describe, expect, test } from "vitest";
import { bucketKey, bucketOf, inRollout, RESOLUTION } from "./bucket";

const subjects = Array.from({ length: 10_000 }, (_, i) => `user-${i}`);

function rolloutShare(percent: number, salt = "feature"): number {
  const hits = subjects.filter((subject) => inRollout(bucketOf(bucketKey(salt, subject)), percent));
  return (hits.length / subjects.length) * 100;
}

describe("bucketOf", () => {
  test("is deterministic", () => {
    const key = bucketKey("feature", "user-1");
    const first = bucketOf(key);

    for (let i = 0; i < 100; i++) {
      expect(bucketOf(key)).toBe(first);
    }
  });

  test("stays within range", () => {
    for (const subject of subjects.slice(0, 500)) {
      const value = bucketOf(bucketKey("f", subject));
      expect(value).toBeGreaterThanOrEqual(0);
      expect(value).toBeLessThan(RESOLUTION);
    }
  });

  /**
   * The regression this exists for is invisible at runtime and catastrophic in
   * production: swap the hash, or reorder the key components, and every subject
   * is silently re-bucketed mid-rollout. Nothing throws, no test about
   * *distribution* fails, and the only symptom is that the cohort you were
   * measuring quietly became a different cohort.
   *
   * These values were generated by this implementation. If a change makes them
   * fail, that change re-buckets every subject of every deployed application —
   * so updating the table is only correct alongside a deliberate migration.
   */
  test("pinned digests — changing these re-buckets every subject in production", () => {
    expect(bucketOf(bucketKey("new-checkout", "user-1"))).toBe(bucketOf("new-checkout:user-1"));

    const pinned: Record<string, number> = {
      "new-checkout:user-1": 2175,
      "new-checkout:user-2": 7932,
      "pricing-redesign:user-1": 8314,
      "pricing-redesign:user-2": 8970,
      "new-checkout:": 5428,
      "new-checkout:0192f0c0-0000-7000-8000-000000000000": 2181,
    };

    for (const [key, bucket] of Object.entries(pinned)) {
      expect(bucketOf(key), key).toBe(bucket);
    }
  });
});

describe("bucketKey", () => {
  test("is salt then subject", () => {
    expect(bucketKey("new-checkout", "user-1")).toBe("new-checkout:user-1");
  });
});

describe("inRollout", () => {
  test("0 excludes everyone and 100 includes everyone", () => {
    expect(rolloutShare(0)).toBe(0);
    expect(rolloutShare(100)).toBe(100);
  });

  test("approximates the requested percentage", () => {
    for (const percent of [1, 5, 10, 25, 50, 75, 99]) {
      expect(Math.abs(rolloutShare(percent) - percent)).toBeLessThan(1.5);
    }
  });

  test("is monotonic — raising a rollout never removes a subject", () => {
    let previous = new Set<string>();

    for (const percent of [0, 1, 5, 10, 25, 50, 75, 100]) {
      const included = new Set(
        subjects.filter((s) => inRollout(bucketOf(bucketKey("f", s)), percent)),
      );
      for (const s of previous) expect(included.has(s)).toBe(true);
      previous = included;
    }
  });

  test("different salts select different subjects at the same percentage", () => {
    const a = subjects.filter((s) => inRollout(bucketOf(bucketKey("a", s)), 20));
    const b = subjects.filter((s) => inRollout(bucketOf(bucketKey("b", s)), 20));

    expect(a).not.toEqual(b);
    // Independent 20% samples overlap around 4% of the population, i.e. about a
    // fifth of either set — not the whole of it.
    const overlap = a.filter((s) => b.includes(s)).length;
    expect(overlap / a.length).toBeLessThan(0.4);
  });

  test("guards against out-of-range percentages", () => {
    expect(inRollout(0, -10)).toBe(false);
    expect(inRollout(RESOLUTION - 1, 200)).toBe(true);
  });
});
